# This is the main application.properties that holds all the common properties of my application

# This is used to tell Spring which profile we want to be active

#--spring.profiles.active=test,dev
#spring.profiles.active=dev,test

spring.application.name=learning-springboot
custom.property=123
